version: '3.8'

services:
  amlight:
    container_name: amlight
    image: amlight
    restart: always
    privileged: true
    ports:
      - 6653:6653
      - 8181:8181
  sax:
    container_name: sax
    image: sax
    restart: always
    privileged: true
    ports:
      - 6654:6654
      - 8282:8181
  tenet:
    container_name: tenet
    image: tenet
    restart: always
    privileged: true
    ports:
      - 6655:6655
      - 8383:8181
  mininet:
    container_name: mininet
    image: mininet
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules:/lib/modules
    depends_on:
      - amlight
      - sax
      - tenet

