version: '3.8'

services:
  mongo:
    container_name: sdx_mongo
    image: sdx_mongo
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.10
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db

networks:
  kytos_network:
    external: true
