version: '3.9'

services:

  amlight:
    container_name: amlight
    image: amlight
    privileged: true
    tty: true
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.2
    ports:
      - 6653:6653
      - 8181:8181
    volumes:
      - ./tests:/tests
      - ./scripts:/scripts
      - ./etc/kytos:/etc/kytos
      - ./container-sdx-lc/logs/amlight:/var/log/amlight
    env_file: 
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_USERNAME: 'amlight_user'
      MONGO_PASSWORD: 'amlight_pwd'
      MONGO_DBNAME: 'amlight'
      MODEL_VERSION: ${MODEL_VERSION}
      OXPO_ID: 1
      OXPOS: ${SDX_OXPOS}
      OXPO_NAMES: ${SDX_OXPO_NAMES}
      OXPO_URLS: ${SDX_OXPO_URLS}
      # 
      SDXTOPOLOGY_VALIDATOR: ${SDX_TOPOLOGY_VALIDATOR}
      SDXLC_URLS: ${SDX_LC_URLS}
      KYTOS_PROVISION: ${KYTOS_PROVISION}
      KYTOS_TOPOLOGY: ${KYTOS_TOPOLOGY}
      KYTOSSDX_TOPOLOGY: ${KYTOS_SDX_TOPOLOGY}
      KYTOSSDX_VERSION_CONTROL: ${KYTOS_SDX_VERSION_CONTROL}
    depends_on:
      - mongo-ready
    entrypoint: ["/scripts/amlight_sdx_lc_kytos.sh"]

  sax:
    container_name: sax
    image: sax
    privileged: true
    tty: true
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.3
    ports:
      - 6654:6653
      - 8282:8181
    volumes:
      - ./tests:/tests
      - ./scripts:/scripts
      - ./etc/kytos:/etc/kytos
    env_file: 
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_USERNAME: 'sax_user'
      MONGO_PASSWORD: 'sax_pwd'
      MONGO_DBNAME: 'sax'
      MODEL_VERSION: ${MODEL_VERSION}
      OXPO_ID: 2
      OXPOS: ${SDX_OXPOS}
      OXPO_NAMES: ${SDX_OXPO_NAMES}
      OXPO_URLS: ${SDX_OXPO_URLS}
      # 
      SDXTOPOLOGY_VALIDATOR: ${SDX_TOPOLOGY_VALIDATOR}
      SDXLC_URLS: ${SDX_LC_URLS}
      KYTOS_PROVISION: ${KYTOS_PROVISION}
      KYTOS_TOPOLOGY: ${KYTOS_TOPOLOGY}
      KYTOSSDX_TOPOLOGY: ${KYTOS_SDX_TOPOLOGY}
      KYTOSSDX_VERSION_CONTROL: ${KYTOS_SDX_VERSION_CONTROL}
    depends_on:
      - mongo-ready
    entrypoint: ["/scripts/sax_sdx_lc_kytos.sh"]

  tenet:
    container_name: tenet
    image: tenet
    privileged: true
    restart: always
    tty: true
    networks:
      kytos_network:
        ipv4_address: 192.168.0.4
    ports:
      - 6655:6653
      - 8383:8181
    volumes:
      - ./tests:/tests
      - ./scripts:/scripts
      - ./etc/kytos:/etc/kytos
    env_file: 
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_USERNAME: 'tenet_user'
      MONGO_PASSWORD: 'tenet_pwd'
      MONGO_DBNAME: 'tenet'
      MODEL_VERSION: ${MODEL_VERSION}
      OXPO_ID: 3
      OXPOS: ${SDX_OXPOS}
      OXPO_NAMES: ${SDX_OXPO_NAMES}
      OXPO_URLS: ${SDX_OXPO_URLS}
      # 
      SDXTOPOLOGY_VALIDATOR: ${SDX_TOPOLOGY_VALIDATOR}
      SDXLC_URLS: ${SDX_LC_URLS}
      KYTOS_PROVISION: ${KYTOS_PROVISION}
      KYTOS_TOPOLOGY: ${KYTOS_TOPOLOGY}
      KYTOSSDX_TOPOLOGY: ${KYTOS_SDX_TOPOLOGY}
      KYTOSSDX_VERSION_CONTROL: ${KYTOS_SDX_VERSION_CONTROL}
    depends_on:
      - mongo-ready
    entrypoint: ["/scripts/tenet_sdx_lc_kytos.sh"]

  sdx-test:
    container_name: sdx-test
    image: sdx-test
    privileged: true
    tty: true
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.5
    ports:
      - 6656:6653
      - 8484:8181
    volumes:
      - ./tests:/tests
      - ./scripts:/scripts
      - ./etc/kytos:/etc/kytos
    env_file: 
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_USERNAME: 'sdx_test_user'
      MONGO_PASSWORD: 'sdx_test_pwd'
      MONGO_DBNAME: 'sdx_test'
      MODEL_VERSION: ${MODEL_VERSION}
      OXPO_ID: 0
      OXPOS: ${SDX_OXPOS}
      OXPO_NAMES: ${SDX_OXPO_NAMES}
      OXPO_URLS: ${SDX_OXPO_URLS}
      # 
      SDXTOPOLOGY_VALIDATOR: ${SDX_TOPOLOGY_VALIDATOR}
      SDXLC_URLS: ${SDX_LC_URLS}
      KYTOS_PROVISION: ${KYTOS_PROVISION}
      KYTOS_TOPOLOGY: ${KYTOS_TOPOLOGY}
      KYTOSSDX_TOPOLOGY: ${KYTOS_SDX_TOPOLOGY}
      KYTOSSDX_VERSION_CONTROL: ${KYTOS_SDX_VERSION_CONTROL}
    depends_on:
      - mongo-ready
    entrypoint: ["/scripts/test_sdx_lc_kytos.sh"]


  mongo1t:
    container_name: mongo1t
    image: sdx-mongo
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.6
    ports:
      - 27027:27027
    volumes:
      - ./os_base/mongo_base:/mongo_base
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27027" ]
    env_file:
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INIT_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INIT_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_DBNAME: ${ROOT_DB}

  mongo2t:
    container_name: mongo2t
    image: sdx-mongo
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.7
    ports:
      - 27028:27028
    volumes:
      - ./os_base/mongo_base:/mongo_base
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27028" ]
    env_file:
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INIT_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INIT_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_DBNAME: ${ROOT_DB}

  mongo3t:
    container_name: mongo3t
    image: sdx-mongo
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.8
    ports:
      - 27029:27029
    volumes:
      - ./os_base/mongo_base:/mongo_base
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27029" ]
    env_file:
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INIT_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INIT_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_DBNAME: ${ROOT_DB}

  mongo-setup:
    container_name: mongo-rs-init
    image: sdx-mongo
    restart: on-failure
    networks:
      kytos_network:
        ipv4_address: 192.168.0.9
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/scripts/rs-init.sh"]
    env_file:
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INIT_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INIT_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_DBNAME: ${ROOT_DB}
    depends_on:
      - mongo1t
      - mongo2t
      - mongo3t

  mongo-ready:
    container_name: mongo-test-ready
    image: sdx-mongo
    restart: on-failure
    networks:
      kytos_network:
        ipv4_address: 192.168.0.10
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/scripts/rs-add.sh"]
    env_file:
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INIT_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INIT_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MONGO_DBNAME: ${ROOT_DB}
    depends_on:
      - mongo-setup

  mininet:
    container_name: mininet
    image: mininet
    privileged: true
    tty: true
    networks:
      kytos_network:
        ipv4_address: 192.168.0.11
    volumes:
      - /lib/modules:/lib/modules
    depends_on:
      - amlight
      - sax
      - tenet

  rabbitmq3:
    container_name: "rabbitmq"
    image: sdx-rabbit
    hostname: "rabbitmq-host"
    networks:
      kytos_network:
        ipv4_address: 192.168.0.12
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  validator:
    container_name: validator
    image: validator
    privileged: true
    tty: true
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.14
    ports:
      - 8000:8000
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "gunicorn", "validator.app:app", "-b", "0.0.0.0:8000" ]

  amlight-sdx-lc:
    container_name: amlight-sdx-lc
    image: amlight-sdx-lc
    privileged: true
    tty: true
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.15
    ports:
      - 8081:8080
    volumes:
      - ./container-sdx-lc/logs/amlight:/var/log
      - ./scripts:/scripts
    env_file: 
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      # Oxpo variables
      OXPO_ID: 1
      OXPOS: ${SDX_OXPOS}
      OXPO_NAMES: ${SDX_OXPO_NAMES}
      OXPO_URLS: ${SDX_OXPO_URLS}
      KYTOS_PROVISION: ${KYTOS_PROVISION}
      # SDX_LC Variables
      DB_NAME: ${SDX_LC_DB_NAME}
      DB_CONFIG_TABLE_NAME: 'amlight-sdx-lc'
      SDXLC_MONGO_USERNAME: ${SDX_LC_DB_USER}
      SDXLC_MONGO_PASSWOD: ${SDX_LC_DB_PASS}
      SDXLC_DOMAINS: ${SDX_LC_DOMAINS}
      SDXLC_HOST: '192.168.0.15'
      SDXLC_PORT: 8080
      SDXLC_VERSION: ${SDX_LC_VERSION}
      # change to local controller host name
      PUB_TOPIC: ${SDX_LC_PUB_TOPIC}
      PUB_QUEUE: ${SDX_LC_PUB_QUEUE}
      SUB_QUEUE: ${SDX_LC_SUB_QUEUE}
      SUB_EXCHANGE: ${SDX_LC_SUB_EXCHANGE}
      # change to local controller config (lc1_q1)
      SUB_TOPIC: ${SDX_LC_SUB_TOPIC}
      MQ_NAME: ${SDX_LC_MQ_NAME}
      MQ_HOST: ${SDX_LC_MQ_HOST}
      MQ_PORT: ${SDX_LC_MQ_PORT}
      MQ_SRVC: ${RABBITMQ_DEFAULT_HOST}
      MQ_USER: ${RABBITMQ_DEFAULT_USER}
      MQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      DOMAIN_CONTROLLER_URL: ${DOMAIN_CONTROLLER_URL}
      DOMAIN_CONTROLLER_PULL_URL: ${DOMAIN_CONTROLLER_PULL_URL}
      DOMAIN_CONTROLLER_PULL_INTERVAL: ${DOMAIN_CONTROLLER_PULL_INTERVAL}
    depends_on:
      - mongo-ready
      - rabbitmq3
    entrypoint: ["python3", "-m", "swagger_server"]

  sax-sdx-lc:
    container_name: sax-sdx-lc
    image: sax-sdx-lc
    privileged: true
    tty: true
    restart: always
    networks:
      kytos_network:
        ipv4_address: 192.168.0.16
    ports:
      - 8082:8080
    volumes:
      - ./container-sdx-lc/logs/sax:/var/log
      - ./scripts:/scripts
    env_file: 
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      # Oxpo variables
      OXPO_ID: 2
      OXPOS: ${SDX_OXPOS}
      OXPO_NAMES: ${SDX_OXPO_NAMES}
      OXPO_URLS: ${SDX_OXPO_URLS}
      KYTOS_PROVISION: ${KYTOS_PROVISION}
      # SDX_LC Variables
      DB_NAME: ${SDX_LC_DB_NAME}
      DB_CONFIG_TABLE_NAME: 'sax-sdx-lc'
      SDXLC_MONGO_USERNAME: ${SDX_LC_DB_USER}
      SDXLC_MONGO_PASSWOD: ${SDX_LC_DB_PASS}
      SDXLC_DOMAINS: ${SDX_LC_DOMAINS}
      SDXLC_HOST: '192.168.0.16'
      SDXLC_PORT: 8080
      SDXLC_VERSION: ${SDX_LC_VERSION}
      # change to local controller host name
      PUB_TOPIC: ${SDX_LC_PUB_TOPIC}
      PUB_QUEUE: ${SDX_LC_PUB_QUEUE}
      SUB_QUEUE: ${SDX_LC_SUB_QUEUE}
      SUB_EXCHANGE: ${SDX_LC_SUB_EXCHANGE}
      # change to local controller config (lc1_q1)
      SUB_TOPIC: ${SDX_LC_SUB_TOPIC}
      MQ_NAME: ${SDX_LC_MQ_NAME}
      MQ_HOST: ${SDX_LC_MQ_HOST}
      MQ_PORT: ${SDX_LC_MQ_PORT}
      MQ_SRVC: ${RABBITMQ_DEFAULT_HOST}
      MQ_USER: ${RABBITMQ_DEFAULT_USER}
      MQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      DOMAIN_CONTROLLER_URL: ${DOMAIN_CONTROLLER_URL}
      DOMAIN_CONTROLLER_PULL_URL: ${DOMAIN_CONTROLLER_PULL_URL}
      DOMAIN_CONTROLLER_PULL_INTERVAL: ${DOMAIN_CONTROLLER_PULL_INTERVAL}
    depends_on:
      - mongo-ready
      - rabbitmq3
    entrypoint: ["python3", "-m", "swagger_server"]

  tenet-sdx-lc:
    container_name: tenet-sdx-lc
    image: tenet-sdx-lc
    privileged: true
    restart: always
    tty: true
    networks:
      kytos_network:
        ipv4_address: 192.168.0.17
    ports:
      - 8083:8080
    volumes:
      - ./container-sdx-lc/logs/tenet:/var/log
      - ./scripts:/scripts
    env_file: 
      - .env
    environment:
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_HOST_SEEDS: ${MONGO_HOST_SEEDS}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      # Oxpo variables
      OXPO_ID: 3
      OXPOS: ${SDX_OXPOS}
      OXPO_NAMES: ${SDX_OXPO_NAMES}
      OXPO_URLS: ${SDX_OXPO_URLS}
      KYTOS_PROVISION: ${KYTOS_PROVISION}
      # SDX_LC Variables
      DB_NAME: ${SDX_LC_DB_NAME}
      DB_CONFIG_TABLE_NAME: 'tenet-sdx-lc'
      SDXLC_MONGO_USERNAME: ${SDX_LC_DB_USER}
      SDXLC_MONGO_PASSWOD: ${SDX_LC_DB_PASS}
      SDXLC_DOMAINS: ${SDX_LC_DOMAINS}
      SDXLC_HOST: '192.168.0.17'
      SDXLC_PORT: 8080
      SDXLC_VERSION: ${SDX_LC_VERSION}
      # change to local controller host name
      PUB_TOPIC: ${SDX_LC_PUB_TOPIC}
      PUB_QUEUE: ${SDX_LC_PUB_QUEUE}
      SUB_QUEUE: ${SDX_LC_SUB_QUEUE}
      SUB_EXCHANGE: ${SDX_LC_SUB_EXCHANGE}
      # change to local controller config (lc1_q1)
      SUB_TOPIC: ${SDX_LC_SUB_TOPIC}
      MQ_NAME: ${SDX_LC_MQ_NAME}
      MQ_HOST: ${SDX_LC_MQ_HOST}
      MQ_PORT: ${SDX_LC_MQ_PORT}
      MQ_SRVC: ${RABBITMQ_DEFAULT_HOST}
      MQ_USER: ${RABBITMQ_DEFAULT_USER}
      MQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      DOMAIN_CONTROLLER_URL: ${DOMAIN_CONTROLLER_URL}
      DOMAIN_CONTROLLER_PULL_URL: ${DOMAIN_CONTROLLER_PULL_URL}
      DOMAIN_CONTROLLER_PULL_INTERVAL: ${DOMAIN_CONTROLLER_PULL_INTERVAL}
    depends_on:
      - mongo-ready
      - rabbitmq3
    entrypoint: ["python3", "-m", "swagger_server"]

  sdx-controller:
    container_name: sdx-controller
    image: sdx-controller
    privileged: true
    restart: always
    depends_on:
      - mongo-ready
      - rabbitmq3
    tty: true
    networks:
      kytos_network:
        ipv4_address: 192.168.0.20
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      # Use mongodb-service specified above.  Note that we do not use
      # the same MONGODB_CONNSTRING variable from .env here, because
      # that is helpful for running unit/integration tests.
      MONGODB_CONNSTRING: ${MONGODB_CONNSTRING}
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      SDX_VERSION: ${SDX_VERSION}
      MQ_HOST: ${SDX_CONTROLLER_MQ_HOST}
      MQ_SRVC: ${RABBITMQ_DEFAULT_HOST}
      MQ_USER: ${RABBITMQ_DEFAULT_USER}
      MQ_PASS: ${RABBITMQ_DEFAULT_PASS}
      SUB_TOPIC: ${SDX_CONTROLLER_SUB_TOPIC}
      SUB_QUEUE: ${SDX_CONTROLLER_SUB_QUEUE}
      DB_NAME: ${SDX_LC_DB_NAME}
      DB_CONFIG_TABLE_NAME: 'sdx-controller'
    entrypoint: ["python3", "-m", "swagger_server"]

networks:
  kytos_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

volumes:
  persistent:
