version: '3.9'

services:

  mongolc:
    container_name: mongolc
    image: mongo_lc
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      kytos_network:
        ipv4_address: 192.168.0.9

  sdx-lc:
    container_name: sdx-lc
    image: sdx-lc
    tty: true
    networks:
      kytos_network:
        ipv4_address: 192.168.0.14
    depends_on:
      - mongolc

    environment:
      - PYTHONUNBUFFERED=1
      - MODE=dev
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - SERVER_URL=0.0.0.0
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pass
      - PORT=8080

    ports:
      - "8080:8080"


networks:
  kytos_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

volumes:
  persistent:
